# Generated by Django 4.2.4 on 2023-08-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcodeforces',
            name='difficulty_level',
            field=models.CharField(verbose_name='уровень сложности'),
        ),
        migrations.AlterField(
            model_name='taskcodeforces',
            name='number_of_solutions',
            field=models.CharField(verbose_name='количество решений'),
        ),
        migrations.AlterField(
            model_name='taskcodeforces',
            name='task_url',
            field=models.CharField(verbose_name='ссылка на задание'),
        ),
    ]
