# Generated by Django 4.2.4 on 2023-08-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0002_alter_taskcodeforces_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcodeforces',
            name='task_topic',
            field=models.CharField(max_length=200, verbose_name='тема задачи'),
        ),
    ]
