# Generated by Django 4.2.5 on 2023-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0003_alter_taskcodeforces_task_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcodeforces',
            old_name='difficulty_level',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='taskcodeforces',
            old_name='number_of_solutions',
            new_name='solved_count',
        ),
        migrations.RenameField(
            model_name='taskcodeforces',
            old_name='task_topic',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='taskcodeforces',
            name='task_number',
        ),
        migrations.AddField(
            model_name='taskcodeforces',
            name='contest_id',
            field=models.CharField(default=0, max_length=20, verbose_name='ID задания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcodeforces',
            name='index',
            field=models.CharField(default=0, max_length=20, verbose_name='индекс задания'),
            preserve_default=False,
        ),
    ]
