# Generated by Django 4.2.5 on 2023-09-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0004_rename_difficulty_level_taskcodeforces_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcodeforces',
            name='rating',
            field=models.CharField(blank=True, null=True, verbose_name='уровень сложности'),
        ),
        migrations.AlterField(
            model_name='taskcodeforces',
            name='solved_count',
            field=models.CharField(blank=True, null=True, verbose_name='количество решений'),
        ),
        migrations.AlterField(
            model_name='taskcodeforces',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='тема задачи'),
        ),
    ]
