# Generated by Django 4.2.5 on 2023-09-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeforces', '0005_alter_taskcodeforces_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcodeforces',
            name='title',
            field=models.CharField(max_length=300, verbose_name='название задания'),
        ),
    ]
